"""
xAI Third-Party Service Integration
"""
import logging
import os

import openai

from .. import third_party
from .. import commons

class AzureOpenAI(third_party.ThirdPartyBase):
    """
    xAI class that extends ThirdPartyBase.
    
    This class represents a third-party service for explainable AI functionalities.
    It provides methods to retrieve API key slot information and AI engine information.
    """

    def __init__(self):
        super().__init__("AzureOpenAI")
        self._logger = logging.getLogger(__name__ + ".AzureOpenAI")
        self._logger.info("Initializing AzureOpenAI.")
        self._client_dict = {}

    def get_apikey_slot_info_list(self) -> list[third_party.ApiKeySlotInfo]:
        return [
            third_party.ApiKeySlotInfo(
                apikey_slot_id="azure_openai",
                name="Azure OpenAI"
            )
        ]

    def get_aiengine_info_list(self) -> list[third_party.AIEngineInfo]:
        return [
            third_party.AIEngineInfo(
                aiengine_id="azure_openai",
                name="Azure OpenAI",
                apikey_slot_id_list=["azure_openai"],
                arg_list=[
                    third_party.AIEngineArgInfo(
                        arg_id="model_name",
                        name="Deployment Name",
                        required=True,
                        ),
                    third_party.AIEngineArgInfo(
                        arg_id="system_prompt",
                        name="System Prompt",
                        required=False,
                    )
                ]
            )
        ]

    def generate_response(
        self,
        _aiengine_id: str,
        aiengine_arg_dict: dict[str, str],
        apikey_list: list[str],
        role_name: str,
        conversation_history: list[third_party.Message]
    ) -> str:
        """
        Generates a response from the AI engine.
        
        Args:
            aiengine_id (str): The ID of the AI engine to use.
            aiengine_args (dict[str, str]): Arguments for the AI engine.
            apikey_list (list[str]): List of API keys for authentication.
            role_name (str): The name of the role for the AI.
            conversation_history (list[Message]): A list representing the current conversation history.
        
        Returns:
            str: The response generated by the AI engine.
        """

        assert (len(apikey_list) == 1), "XAI requires exactly one API key."

        deployment_name = aiengine_arg_dict["model_name"]
        system_prompt = aiengine_arg_dict.get("system_prompt", "")
        apikey = apikey_list[0]

        azure_endpoint = commons.read_str(os.path.join('tmp','azure_endpoint.txt')) # TODO
        api_version = '2024-12-01-preview' # TODO
        client = self._get_client(
            apikey=apikey,
            azure_endpoint=azure_endpoint,
            api_version=api_version
        )

        messages = [{"role": "system", "content": system_prompt}]
        for msg in conversation_history:
            if msg.sender == role_name:
                messages.append({"role": "assistant", "content": msg.content.strip()})
            else:
                # messages.append({"role": "user", "content": msg['text']})
                reuse_content = True
                if len(messages) <= 0:
                    reuse_content = False
                if reuse_content and len(messages) >= 1 and messages[-1]["role"] != "user":
                    reuse_content = False

                if reuse_content:
                    messages[-1]["content"] += '\n\n'
                else:
                    messages.append({"role": "user", "content": ""})
                messages[-1]["content"] += f'{msg.sender} said:\n{msg.content.strip()}'

        # Log the constructed messages list for debugging, if necessary (optional)
        # logging.debug(f"Constructed messages for Azure OpenAI: {messages}")

        try:
            response = client.chat.completions.create(
                model=deployment_name,
                messages=messages
            )
            if response.choices and len(response.choices) > 0:
                generated_text = response.choices[0].message.content.strip()
                # Log the successful generation, possibly with a summary of input if not too verbose
                logging.info(f"Successfully generated response from Azure OpenAI for role {role_name}.")
                return generated_text
            else:
                logging.error(f"No response choices found from Azure OpenAI for role {role_name}.")
                return "Error: No response generated."
        except openai.APIConnectionError as e:
            logging.error(f"Azure OpenAI API connection error for role {role_name}: {e}")
            return f"Error: Could not connect to Azure OpenAI API. Details: {e}"
        except openai.RateLimitError as e:
            logging.error(f"Azure OpenAI API rate limit exceeded for role {role_name}: {e}")
            return f"Error: Azure OpenAI API rate limit exceeded. Details: {e}"
        except openai.AuthenticationError as e:
            logging.error(f"Azure OpenAI API authentication error for role {role_name}: {e}")
            return f"Error: Azure OpenAI API authentication failed. Please check your API key and endpoint. Details: {e}"
        except openai.APIError as e:
            logging.error(f"Azure OpenAI API error for role {role_name}: {e}")
            return f"Error: An unexpected error occurred with the Azure OpenAI API. Details: {e}"
        except Exception as e:
            logging.error(f"An unexpected error occurred for role {role_name}: {e}")
            return f"Error: An unexpected error occurred. Details: {e}"

    def _get_client(self, apikey: str, azure_endpoint: str, api_version: str) -> openai.OpenAI:
        """
        Retrieves or creates an OpenAI client for the given API key.
        
        Args:
            apikey (str): The API key to use for authentication.
        
        Returns:
            openai.OpenAI: An OpenAI client instance.
        """
        if apikey not in self._client_dict:
            client = openai.AzureOpenAI(
                api_key=apikey,
                azure_endpoint=azure_endpoint,
                api_version=api_version,
            )
            self._client_dict[(apikey,azure_endpoint,api_version)] = client
        return self._client_dict[(apikey,azure_endpoint,api_version)]
